### ISSUE TITLE
Visualizar assinatura(s)

### ISSUE THREAD

**Issue by graciano** [juventudes/acampamento#11]
View com "Fulano convida para acampamento..."

- criar uma view que liste assinaturas, com assinaturas "em destaque" para personalidades, ordenadas por prioridade
- criar view individual para as pessoas compartilharem pela web
- pensei em usar gravatar ou algo assim

**Comment by tmadeira** [comment]
Tô roubando essa tarefa porque ela é prioritária para lançarmos o site hoje.
