### ISSUE TITLE
Criar tabela de assinaturas

### ISSUE THREAD

**Issue by tmadeira** [juventudes/acampamento#6]
Proposta de campos: nome, e-mail, telefone, localização (país, estado, cidade), campo para pessoa escrever ocupação/coletivo/escola.

**Comment by tmadeira** [comment]
@graciano, você pode fazer isso e adicionar issues de criar rotas para assinaturas poderem ser adicionadas e visualizadas? (A ideia de "visualizar uma assinatura" seria aquela página "Graciano convida para Acampamento...")

**Comment by tmadeira** [comment]
Mais colunas que acho bom colocar: IP, user agent (além do óbvio datetime).

E acho que temos que ter uma coluna "prioridade" que podemos usar para eventualmente reordenar assinaturas. Tipo, se o Snowden assina, provavelmente vamos querer colocar essa assinatura no início da lista.

**Comment by graciano** [comment]
Pra essa tabela, vou criar uma [migration](https://laravel.com/docs/5.1/migrations) para criar uma tabela assinaturas com estes campos. Depois vai ser criar form de inscrição e etc, vou criar as issues daqui a pouco para isso e vou marcando enquanto eu trabalho.
