### ISSUE TITLE
Garantir que o site esteja todo em português

### ISSUE THREAD

**Issue by tmadeira** [juventudes/acampamento#8]
Vi que tem uma pasta `resources/lang` com uma subpasta `en` onde tem algumas strings traduzidas.

Não sei como internacionalização costuma ser feita no Laravel, mas importante alguém se dedicar a isso. No mínimo pra deixar o negócio em português inicialmente (mensagens de validação de formulário, por exemplo). Depois pode ser o caso de a gente querer lançar versões do site em inglês e espanhol.

**Comment by graciano** [comment]
Posso alterar as views existentes para usar o [helper `trans()`](https://laravel.com/docs/5.1/helpers#method-trans) (de translate), que usam o conteúdo das pastas lang.
Como bons internacionalistas que somos, podemos usar as features de [localization](https://laravel.com/docs/5.1/localization) pra isso em, por exemplo, português e espanhol.

**Comment by tmadeira** [comment]
Adicoinei versões em espanhol e inglês de uma forma meio hacky sugerida por esse cara: https://laracasts.com/discuss/channels/requests/multi-language-routes-and-url/replies/12126
